### ISSUE TITLE
Mob mobility

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/redemption#10]
The mobs should spawn at random locations but inside the scenario. Maybe this can be fixed with a Path2D.

They also need to avoid walls instead of being stuck like this:

![Image](https://user-images.githubusercontent.com/181501/216587542-d8c0bde4-a73d-4763-b8a1-e503d26ab506.png)

The mob will continue to follow the player but, somehow, go around the walls.

**Comment by gerep** [comment]
[This commit](https://github.com/quiet-night-studio/redemption/commit/6b09d370be70a47dc3afe6d5a1f01c6d05e444f8) adds a Navigation2D to the level with some polygons, and a NavigationAgent2D to the mob.



![Image](https://user-images.githubusercontent.com/181501/216942214-7c07052c-531d-4dd8-88b3-3bd130248011.png)

I have to make more tests with those polygons because the mobs are hitting the corners, and sometimes, they get stuck.

**Comment by gerep** [comment]
It is also possible to specify the distance, in pixels, for the edges to connect.


![Image](https://user-images.githubusercontent.com/181501/216942987-31f3f9d1-1944-4a7e-8fcc-75de44b51649.png)

**Comment by gerep** [comment]
💩 



![Image](https://user-images.githubusercontent.com/181501/216944791-0bb68542-d2a9-4225-ba80-24844cf3bf57.png)

**Comment by ProjectEXT** [comment]
![image](https://user-images.githubusercontent.com/96099928/216960685-d497dbc4-050a-4b83-84a7-2051834a026f.png)

**Comment by gerep** [comment]
Improvements!


![Image](https://user-images.githubusercontent.com/181501/217218008-f7002606-2551-4c21-af35-2ef4b2d629a4.png)

I still have a problem. When I add collision to the wall, some mobs are stuck when it hits their corner.

**Comment by gerep** [comment]
Look at those curves!


![Image](https://user-images.githubusercontent.com/181501/217220365-39ac39b8-9bc7-4335-98fc-4b10602d9836.png)

**Comment by gerep** [comment]
Using the mapping in the tile is simple and quicker but not a good fit for everything.

The best solution, so far, is to create the polygons myself, with a bigger distance from the corners.



![Image](https://user-images.githubusercontent.com/181501/217220777-f63b9b29-4984-429f-a712-1d63088ab1ce.png)

This way the mobs will not get stuck in the corners.

The navigation calculates the path based on the centre of the mob, and this was the reason why it was colliding so often.

**Comment by gerep** [comment]
I will re-organise the assets to make them look like in the first image and move this task as done.
