### ISSUE TITLE
Make enemies cause damage

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/redemption#15]
I thought of three possible ways an enemy can damage a player:

- [x] Contact
- [x] Shooting
- [x] Aura

**Comment by gerep** [comment]
It should also make the enemy take damage instead of dying all the time. I have to calculate the damage it takes.

**Comment by ProjectEXT** [comment]
Will every enemy have aura damage, or will they be their own variant? Same for shooting?

**Comment by gerep** [comment]
> Will every enemy have aura damage, or will they be their own variant? Same for shooting?

No. If you check this list here, some have aura damage, some do not. The same will be applied to shooting.

https://github.com/quiet-night-studio/redemption/blob/ef18dd56fb0c4fb643fa2374112c6ef7c4e0b552/scripts/Enemy.gd#L7-L29

**Comment by gerep** [comment]
The shooting is already happening 🥳 

There are still a few things that we need to do to finish this task:

- [ ]  Bullets are colliding, if the player shoots at the enemy's bullet, they will be destroyed.
- [ ]  The enemy's bullet should have a different colour, or format, or both.
- [ ]  The bullet scene has to be configurable: lifetime, speed, and colour (maybe other future characteristics)
