### ISSUE TITLE
Reload issue when reloading and player dies

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/redemption#26]
If the player dies while reloading, it fails with:

```
E 0:01:21.980   resume: Resumed function '_physics_process()' after yield, but class instance is gone. At script: res://scripts/Player.gd:75
  <C++ Error>   Method failed. Returning: Variant()
  <C++ Source>  modules/gdscript/gdscript_function.cpp:1802 @ resume()
```

The problem happens because we have a for loop happening and the scene is reloaded.

**Comment by gerep** [comment]
@ProjectEXT, are you working on this one?

**Comment by ProjectEXT** [comment]
This is solved with the latest change/branch, it is not the _best_ solution, but it is a solution that will work and shouldn't hinder performance.
