### ISSUE TITLE
Player is not showing when restarting the level

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/redemption#32]
When the player dies, it should restart its position on the level, but it is not displayed.

**Comment by ProjectEXT** [comment]
When the player dies, they are being teleported to origin 1,1. The code doing this is in the player script.
<img width="515" alt="Screenshot 2023-06-23 at 9 33 26 AM" src="https://github.com/quiet-night-studio/redemption/assets/96099928/7612c880-bad9-4dff-91b4-710ed8d88173">

Watching the enemies swarm and pile up in the corner of the map is funny to see. :)

**Comment by ProjectEXT** [comment]
Fixe with most recent push [here.](https://github.com/quiet-night-studio/redemption/commit/8fd854064476201546029510eaee037b4413f51a)
