### ISSUE TITLE
Use a round asset to display player's health instead of a bar

### ISSUE THREAD

**Issue by gerep** [quiet-night-studio/redemption#7]
Something similar to Diablo.

![Image](https://user-images.githubusercontent.com/181501/214538282-dcfc830d-3888-4cad-8ed6-55677370becb.png)

**Comment by ProjectEXT** [comment]
Would this health indicator work similar to Diablo as well? I googled how Diablo's system works and funnily enough the first video was an how-to for Godot. Let me know if this helps.
[Make a health bar in the style of Diablo (Godot Tutorial)](https://www.youtube.com/watch?v=2WzA2pwVJ-4)

**Comment by gerep** [comment]
Yes, it would be nice instead of a solid bar going up or down. Thank you for the link. Super helpful.

**Comment by ProjectEXT** [comment]
https://docs.godotengine.org/en/3.1/getting_started/step_by_step/ui_code_a_life_bar.html

We should read this documentation and implement what it's explaining. It seems like a neat way to animate the healthbar. Also, inside the example project it offers, their damage system is more contained than ours - we could take inspiration from how they do it.

**Comment by gerep** [comment]
Thank you for sharing, I'll take a look.
